### ISSUE TITLE
`xcat-inventory diff` output nothing when no diff

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-inventory#121]
currently, the output looks like this:

```
====================BEGIN=====================


--- ['hardware_admin/xcat-inventory/c910f03c05k21/osimage/myosimage.rh7.compute.netboot/definition.yaml']
+++ ['hardware_admin/xcat-inventory/c910f03c05k21/osimage/myosimage.rh7.compute.netboot/definition.yaml']
{}


====================END=====================
```

**Comment by xuweibj** [comment]
Have modified in pull request https://github.com/xcat2/xcat-inventory/pull/107, is still no diff now?

**Comment by immarvin** [comment]
hi @xuweibj , I suggest keep the behavior of `xcat-inventory diff` to be consistent of `diff`, if there is no diff, just print nothing and the return value is 0

**Comment by zet809** [comment]
Another comment is, do we have a backward compatibility for xcat-inventory?
I have update the c910cluster checking script 2 weeks ago, but it doesn't work with latest code. 
```
==>export inventory information to /root/level0/level1/level2/c910cluster//hardware_admin/xcat-inventory/c910f03c05k10/cluster.json
==> XCAT Inventory information modified:
usage: xcat-inventory [-h] [--debug] [-v] [-V] <subcommand> ...
xcat-inventory: error: unrecognized arguments: -n /tmp/M0McAu_cluster.json -o hardware_admin/xcat-inventory/c910f03c05k10/cluster.json
```
It seems the interface is changed:
```
# git config --list | grep difftool
difftool.invdiff.cmd=xcat-inventory diff -n $LOCAL -o $REMOTE
```
I don't mean the current interface is bad, I just didn't want to struggle the maintain the tool that based on xcat-inventory.
