### ISSUE TITLE
xcat-inventory import support multiple keys object passwd

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat-inventory#138]
Task: xcat-inventory import support multiple keys object passwd. column 'key' and 'username' are keys for `passwd` table. In the past, 'key' as passwd object name.
In this enhancement:
1. passwd object name is 'key'.'username'. 
2. In passwd table, 'key' can not be empty, 'username' can be empty. So when import passwd object, the valid object names are 'key'.'username', if import object name like 'key' or 'key.',  will set 'username' as ''.

**Comment by zet809** [comment]
hi, @bybai , I suppose this task is similar with #86 , am I right?

**Comment by bybai** [comment]
Hi @zet809, #86 is about `xcat-inventory export...` functions, in order to support multiple keys, `xcat-inventory import ...` functions should be supported too. so this task is about to `xcat-inventory import ..` part.  Thanks.

**Comment by immarvin** [comment]
hi @bybai , i will cover the import part in new PR

**Comment by immarvin** [comment]
covered in PR https://github.com/xcat2/xcat-inventory/pull/142
