### ISSUE TITLE
[FVT] xcat-inventory could not export/import some object's attributes.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-inventory#161]
With the regression of xcat-inventory bundle, we find that some attributes could not be exported/imported.
The failed cases list is
```
import_validation_node_obj_type
import_validation_node_device_type
import_validation_node_network_info_primarynic_switchport
import_validation_node_role
```
See details of these failed cases, and found following attributes are not exported/imported.
case import_validation_node_obj_type
```
obj_type: group
```
case import_validation_node_device_type
```
device_type:switch
```
case import_validation_node_network_info_primarynic_switchport
```
network_info.primarynic.switchport: 70
```
case import_validation_node_role
```
role:compute
```

**Comment by immarvin** [comment]
please rerun testcases after you have updated object inventory  template
