### ISSUE TITLE
xcat-inventory could not find the correct role for node

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-inventory#171]
When we run the xcat-inventory cases to check the role attribute for node,  it could not find verify the correct role for a compute node. following is the command to run that case. 

```
root@c910f04x35v02:/tmp/import_validation_node_role# /opt/xcat/share/xcat/tools/autotest/testcase/xcat_inventory/validatehelper "node" "bogusnode" "role" "compute" "/tmp/import_validation_node_role"
```
In bogusnode definition, there is role attribute compute
```
   role: compute
```

**Comment by immarvin** [comment]
hi @tingtli , this is a bug in test case, the template file is incorrect, the `role` of node `bogusnode` is `compute`, but `servicenodeftpserver ` and `servicenodenimserver ` are still exists,
```
{
    "node": {
        "bogusnode": {
            "role": "compute",
            "deprecated": {
                "servicenodeftpserver": "setupftp",
                "servicenodenimserver": "setupnim",
                ....
  }
```

after `xcat-inventory import`, there the `bogusnode ` will still exist in `servicenode` table
```
# tabdump servicenode
"bogusnode",,,,,,,,,"setupftp","setupnim",,,,,
```
