### ISSUE TITLE
Separate out source control for osimage 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-inventory#18]
The `export` command by default with no options should export site config...  only when we specify some flag to export `--osimage` should we export it... or `--all` . 

Currently when I am source controlling the configuration on a few management nodes, when osimage changes, the amount of changes created in the export is way too much to provide any value when looking at the changes.  

A single site config change can be missed if we cannot have a granular control of the output

**Comment by whowutwut** [comment]
@gurevichmark Were you working on this? I never created an issue but can you fill in plan?

**Comment by gurevichmark** [comment]
@whowutwut No, I am not currently working on this. It seems the function to import/export individual object types is already there:
```
[root@briggs01 node]# xcat-inventory help export
usage: xcat-inventory export [-t <type>] [-o <name>] [-f <path>]
                             [-s <version>] [--format <format>]

Export the inventory based on the type or name to specified path

Arguments:
  -t <type>, --type <type>
                        Object type to be exported
  -o <name>, --objects <name>
                        Object names to be exported
  -f <path>, --path <path>
                        File path for the inventory objects to export to(not
                        implemented yet)
  -s <version>, --schema-version <version>
                        the schema version
  --format <format>     The content format: json or yaml
[root@briggs01 node]#
```
```
[root@briggs01 node]# xcat-inventory help import
usage: xcat-inventory import [-t <type>] [-o <name>] [-f <path>]
                             [-s <version>] [--dry]

Import the inventory based on the type or name from specified path

Arguments:
  -t <type>, --type <type>
                        Object type to be imported
  -o <name>, --objects <name>
                        Object names to be imported
  -f <path>, --path <path>
                        File path for the inventory objects to import from
  -s <version>, --schema-version <version>
                        the schema version
  --dry                 Dry run mode, nothing will be commited to database
[root@briggs01 node]#
```

**Comment by whowutwut** [comment]
Sorry for the delay, I finally got around to trying this. 

This does not solve my issue...   I'm trying to figure out a use case, right now the osimages on our development cluster changes so frequently that I don't want to source control this piece. 

When I'm using the `-t` option, I have to itemize all the object types into their own file... all I want to do is....
```
xcat-inventory export > cluster1.xcatconfig.json 
xcat-inventory export -t osimage > cluster1.xcatconfig.osimage.json 
```

And if we start to use this and we find that it's not good, we can tweak it some more.. But where do we list out all the possible types that if the end user wants to source control objects into different files, they know they captured all the data?

**Comment by whowutwut** [comment]
Getting a later build does show more info... 
```
[root@briggs01 ~]# xcat-inventory --version
0.1.2 (git commit 1534bdcfb40b2ec21b5a7e1a484aa52dc222df23)
[root@briggs01 ~]# xcat-inventory help export
usage: xcat-inventory export [-t <type>] [-o <name>] [-f <path>]
                             [-s <version>] [--format <format>]

Export the inventory data from xcat database

Arguments:
  -t <type>, --type <type>
                        type of objects to export, valid values:
                        node,passwd,osimage,network,zone,policy,route,site. If
                        not specified, all objects in xcat databse will be
                        exported
  -o <name>, --objects <name>
                        names of the objects to export, delimited with
                        Comma(,). If not specified, all objects of the
                        specified type will be exported
  -f <path>, --path <path>
                        path of the inventory file(not implemented yet)
  -s <version>, --schema-version <version>
                        schema version of the inventory data. Valid values:
                        1.0,latest. If not specified, the "latest" schema
                        version will be used
  --format <format>     format of the inventory data, valid values: json,
                        yaml. json will be used by default if not specified
```

**Comment by whowutwut** [comment]
Still does not work well..... 

Without any options, the order that is created into the output file is the following
1.  network
2. node
3. osimage
4. passwd
5. policy
6. route
7. schema version <--- probably metadata
8. site 

So there's no good way for me to create a single output file that does not contain osimage easily by using the `-t <type>` option with something like this:

```
THEVAR=node,passwd,osimage,network,zone,policy,route,site
for i in ${THEVAR//,/ }; do 
echo $i; 
xcat-inventory export -t $i > `hostname -s`.$i.json; 
done
```

So maybe for now, what we should do is separate out `osimage` and `node` to NOT run by default.... 

The user can then source control 3 files: 
1. `xcat-inventory export > `hostname -s`.json`
2.  `xcat-inventory export -t osimage > `hostname -s`.osimage.json`
3.  `xcat-inventory export -t node > `hostname -s`.node.json`

**Comment by robin2008** [comment]
address it by introducing "-x|--exclude" https://github.com/xcat2/xcat-inventory/pull/25

**Comment by immarvin** [comment]
hi @whowutwut , we plan to split the objects definitions in the cluster configuration from a single file to directories, one for each object, the `def.yaml`  under the object contains the object definition exported by `xcat-inventory export -t <objtype> -o <objname>`,  the directory hierarchy is something like this:
```
[root@c910f03c05k21 site]# tree
.
├── network
│   ├── 192_168_11_0-255_255_255_0
│   │   └── def.yaml
│   └── 192_168_122_0-255_255_255_0
│       └── def.yaml
├── node
│   ├── c910f03c05k21
│   │   ├── def.yaml
│   │   ├── postbootscripts
│   │   │   ├── script1
│   │   │   └── script2
│   │   └── postscripts
│   └── c910f03c05k27
├── osimage
│   ├── rhels6.5-x86_64-netboot-compute
│   └── rhels7.4-x86_64-install-compute
│       ├── def.yaml
│       └── files
│           └── opt
│               └── xcat
│                   └── share
│                       └── xcat
│                           └── install
│                               └── rh
│                                   ├── compute.rhels7.pkglist
│                                   └── compute.rhels7.tmpl
├── password
├── policy
├── route
└── site
    └── def.yaml
```

with this feature, the diff flood after removing one node or osimage will be suppressed,   this is also part of osimage version control design

**Comment by robin2008** [comment]
I think we can close this ticket now, as both the `exclude` and using `--type` to specify more type is supported.
