### ISSUE TITLE
xcat-inventory help usage is not intuitive 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-inventory#19]
The default help message is the following: 
```
[root@stratton01 c910env]# xcat-inventory
usage: xcat-inventory [--debug] [-v] [-V] <subcommand> ...

xCAT inventory management tool

Positional arguments:
  <subcommand>
    export       Export the inventory based on the type or name to specified
                 path
    help         Display help about this program or one of its subcommands.
    import       Import the inventory based on the type or name from specified
                 path

Optional arguments:
  --debug        Prints debugging output into the log file (not implemented
                 yet).
  -v, --verbose  Prints verbose output (not implemented yet).
  -V, --version  Shows the program version and exits.

See "xcat-inventory help COMMAND" for help on a specific command.
[root@stratton01 c910env]#
```

And I see at the end it says: `xcat-inventory help COMMAND` for help on specific command. 

This `COMMAND` should be `SUBCOMMAND`.  

But this is not intuitive.. I would think that help should come last so we can work our way down in the tree.. 

So Ideally I could run.....

1. Get usage: `xcat-inventory help` 
2. Now I want to run export.... : `xcat-inventory export help` or `xcat-inventory export -?` 
3. Now I want to export object names, but I don't know what it's called....    I would do something like: `xcat-inventory export -o -?` or `xcat-inventory export -o --help` ...   But this does not exist. 

If the help is at the end, I could call the help usage, take a look, then just pull up my last command, delete the `help` and replace with the option I want to run, when `help` is in the middle of the command, it makes it more slow to remove that text..

**Comment by robin2008** [comment]
@whowutwut  does `xcat-inventory export -h` meet your requirement?

**Comment by robin2008** [comment]
Here https://github.com/xcat2/xcat-inventory/pull/24 to address it

**Comment by whowutwut** [comment]
@robin2008 Yes, putting the help option at the end of the sub-commands would flow better in my opinion as it will be easy to toggle on and off the help text
