### ISSUE TITLE
xcat-inventory version tracks to xcat-core, does not make sense...

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-inventory#20]
Why are we building xcat-inventory to match the xCAT release version??? 

```
[root@briggs01 ~]# xcat-inventory --version
1.0
[root@briggs01 ~]# rpm -qa | grep xcat-inve
xcat-inventory-2.13.11-snap201802272201.noarch
```

This doesn't make sense at all, it's not part of xCAT-core, so why is it using the same versioning... this is going to be a little problematic to fix..

**Comment by whowutwut** [comment]
This does look better...
```
[root@briggs01 ~]# rpm -ihv xcat-inventory-0.1.2-snap201804040002.noarch.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:xcat-inventory-1:0.1.2-snap201804################################# [100%]
[root@briggs01 ~]# xcat-inventory --version
0.1.2 (git commit 1534bdcfb40b2ec21b5a7e1a484aa52dc222df23)
[root@briggs01 ~]#
```

But it looks like we put this into xcat-dep?

**Comment by whowutwut** [comment]
@robin2008 How do we address existing version of xcat-inventory at the 2.14 version? Maybe we need to bump up the epoch?

**Comment by whowutwut** [comment]
@robin2008 Who created this one? xcat-inventory-2.13.11-snap201802272201.noarch

**Comment by robin2008** [comment]
Yes,  this is only a early try build before we release 0.1, so customer will not have this one.
