### ISSUE TITLE
xcat-inventory generate yaml  inventory file suppressing password 

### ISSUE THREAD

**Issue by Amjadhpc** [xcat2/xcat-inventory#231]
Hello

I am following the guide to xcat-inventory and generated a yaml file for inventory on our cluster.

We would like this file to be uploaded to our internal/privateGit repo .  But the yaml inventory file contains password.

Is there any flag that can be used in xcat-inventory  to generate inventory file and password are suppressed . We know get secret can be used but just checking if xcat-inventory has that functionality

**Comment by gurevichmark** [comment]
There is no `xcat-inventory` flag to suppress the password.
The only thing you can do, that I can think of, is to store the encrypted password in the `passwd` table which will then should get exported into the inventory file 
```
chtab key=system passwd.username=<userid> passwd.password=`openssl passwd -1 <password>`
```
