### ISSUE TITLE
[FEATURE] Request a change to ignore keys that are not relevant to xcat-inventory

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-inventory#27]
The use case here is that I want to add additional metadata into the .yaml file or .json file... 

For example, I want to mark an osimage inactive:
```
diff --git a/osimage/rhels/7.5-alt/install.osimage.yaml b/osimage/rhels/7.5-alt/install.osimage.yaml
index 231195e..d302c0f 100644
--- a/osimage/rhels/7.5-alt/install.osimage.yaml
+++ b/osimage/rhels/7.5-alt/install.osimage.yaml
@@ -1,3 +1,4 @@
+active: 0
 osimage:
   rhels7.5-alternate-ppc64le-CUSTOM-install-compute:
     basic_attributes:
```

However, when I try to import this into xCAT, it fails right away: 
```
[root@briggs01 xcat_clusters]# xcat-inventory import -f osimage/rhels/7.5-alt/install.osimage.yaml
Error: invalid keys found "active"!
```

Can we just ignore keys that are not relevant to xCAT?

**Comment by robin2008** [comment]
what does `active` mean here,  an inactive osimage in yaml will not be imported to DB?

And I just think maybe we can use comments in yaml file, instead of a valid key, it will cause things complext when parsing the file.

If you just want to to declare an osimage not be imported in this file, we can give some meta declarative announcement, just like `#@ignore` then we can have an preprocessing before the normal logic.

**Comment by whowutwut** [comment]
@robin2008 `active` doesn't mean anything.     Looking at  a  large use case where we may have  hundreds of osimage that are in source control...  we might tag them based on the internal release names, we  might tag them based on the team that controls it... 

So just trying to play around with how we can store meta data into the osimage that would  allow us to  run a script to import only those osimages that we need.... 

Possible tags.... 

### Control Release so we only import osimages for our currently release
cs14a, cs14b, cs15a, cs15b, cs16a, cs16b, cs17a, cs17b, cs18a...  

### Control teams
xcat, ist, wsc, etc...

So if I wanted to leverage the shared source control repo, and wanted to import IST definitions from cs17b release, i could be able to find those osimages and load ONLY those ones... 

This is just all brainstorming..  @immarvin  Yes, Let me try to solve this using comments instead.

**Comment by robin2008** [comment]
tag is good here for your using, now both table `osimage` and `linuximage` has `comment` column, we might leverage one as a dedicate tags column without adding new column.
