### ISSUE TITLE
[FEATURE REQUEST] Include the xcat version into the source control output

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-inventory#35]
A situation came up today when I was looking into the source control history to find out when a node entry got added into the xCATDB.  It looks like it was added 1 month after code was added to block this kind of entry from going into the DB. 

While I can't say 100% that we did not update xCAT for 1 month to the latest development build, it seems HIGHLY unlikely that the code was tracking 1 month back, we update every day if not at least once a week. 

So in order to prove this, we need to have the xCAT version stored into an entry into the JSON or YAML file.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-inventory/pull/38

**Comment by immarvin** [comment]
hi @whowutwut , besides xCAT version, xcat-inventory leverage the schema version to support the xcat DB schema or inventory layout change  

each exported inventory file has a `schema_version` in the yaml/json file,  this logs the version of the schema used to export the objects. while import, the object will be imported with the schema version included in the inventory file

```
[root@c910f03c05k21 xCAT-Incubator]# xcat-inventory export -t osimage -o compute
{
    "osimage": {
        "compute": {
            "basic_attributes": {
                "arch": "ppc64le",
                "distribution": "rhels6.4",
                "osdistro": "rhels7.3-ppc64le",
                "osname": "linux"
            },
            "imagetype": "linux",
            "package_selection": {
                "otherpkglist": "/install/templates/compute/myotherpkglist",
                "pkgdir": "/install/rhels7.3/x86_64,/install/software/otherpkgs,/install/software/saltstack,/install/software/epel,/install/software/rhel-7-server,/install/software/rhel-7-server-optional-rpms",
                "pkglist": "/opt/xcat/share/xcat/install/rh/compute.rhels7.pkglist"
            },
            "provision_mode": "install",
            "role": "compute",
            "template": "/install/templates/compute/compute.tmpl"
        }
    },
    "schema_version": "1.0"
}
#Version 2.14.1 (git commit ac941fd2501e8a581bfcc4c79b9301f6ec37ab93, built Mon May 21 06:15:46 EDT 2018)

```

We are planning to provide a table to present the relationship between schema version and xCAT versions, something like this:
```
schema_version                xCAT versions
           1.0                               <= 2.14
           2.0                               >=2.14.1
           ...

```

**Comment by whowutwut** [comment]
@immarvin Great, what happens if we try and import a 2.0 schema to a xCAT version < 2.14?
