### ISSUE TITLE
[feature] environment variable support in xcat-inventory export for osimage

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-inventory#46]
export the osimage definition from DB to osimage inventory file  if environment variables `GITREPO`, `SWDIR` are specified

* convert the absolute paths in osimage definition in xCAT DB to paths with environment variables in osimage inventory file

* do not export the `environvar` attribute  to inventory file

**Comment by tingtli** [comment]
https://github.com/xcat2/xcat-core/pull/5314

**Comment by immarvin** [comment]
PR https://github.com/xcat2/xcat-inventory/pull/58/files

**Comment by robin2008** [comment]
https://github.com/xcat2/xcat-inventory/pull/58 is merged.
