### ISSUE TITLE
[feature request]investigate the tools or options to `diff` inventory files based on object/keys in yaml/json 

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-inventory#7]
current `git diff` is text line based, i will check whether there is some tools or options to `diff` the file based on the object/keys in yaml/json file

**Comment by zet809** [comment]
Need to discuss more about the content plan to do in 2.14.3

**Comment by immarvin** [comment]
https://github.com/xcat2/xcat-inventory/issues/82 created a script to present an informative output

**Comment by immarvin** [comment]
https://github.com/xcat2/xcat-inventory/issues/84 is to refine the output style of inventory diff output
