### ISSUE TITLE
Not every attributes exported for node definition

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-inventory#77]
I ran xcat-inventory command to export switch node defintion to yaml file, then import to another MN,  a lot of attributes are miss
````
[root@boston01 xcatpost]# lsdef mid21
Object name: mid21
    groups=switch,mid_switch
    ip=172.17.21.100
    mac=24:8a:07:a6:15:88
    mgt=switch
    nodetype=switch
    password=admin
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    status=ip_configed
    switch=core01
    switchport=21
    switchtype=Mellanox
    usercomment=Mellanox MSX1410,MLNX-OS,SWv3.5.1006
    username=admin
[root@boston01 xcatpost]# xcat-inventory export -t node -o mid21 --format yaml > /tmp/mid21.yaml

[root@boston01 xcatpost]# sum /tmp/mid21.yaml
33604     1

````
import to boston36:
```
[root@boston36 p8le]# sum mid21.yaml
33604     1

[root@boston36 p8le]# xcat-inventory import -f ./mid21.yaml 
Importing object: mid21
Inventory import successfully!
[root@boston36 p8le]# lsdef mid21
Object name: mid21
    groups=switch,mid_switch
    ip=172.17.21.100
    mac=24:8a:07:a6:15:88
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    switchport=21
    usercomment=Mellanox MSX1410,MLNX-OS,SWv3.5.1006
```

**Comment by immarvin** [comment]
hi @cxhong , the missing attributes are the attributes of groups `mid_switch`, `lsdef` inherits group attributes but `xcat-inventory` only exports the raw database data, it does not inherit the group attributes

we plan to add some kind of dependency between the objects like groups and nodes, and export/import the objects as well as their dependency objects.
will add a ticket to on this

**Comment by immarvin** [comment]
the ticket is https://github.com/xcat2/xcat-inventory/issues/78

**Comment by whowutwut** [comment]
@immarvin If they are exported in the groups, we may be okay. We just need to export the correct groups and the attributes should be the same.  We do want to preserve the groups in the export..

**Comment by robin2008** [comment]
Close it first unless we found the real missing attribute.
