### ISSUE TITLE
Request default of export to be --format=yaml 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-inventory#88]
Is there a benefit for using JSON over YAML? 
If not, I think the files are more easily modified  in source control if the default export format is YAML.

**Comment by robin2008** [comment]
There is no special considering,  as we want the inventory data model is a base of future xCAT, so json is more friendly for machine. For example, we canquick load the JSON data for Machine Learning.

And current, most the use case is better to use YAML, we can change the default to YAML.

**Comment by robin2008** [comment]
And I think no need to consider much about the impact after the default behavior changing as current install base is small.

**Comment by immarvin** [comment]
yes, yaml is more friendly for human being , will consider this modification in next release. Since currently there is not many external customer, we do not need to consider backward compatibility

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-inventory/pull/98
