### ISSUE TITLE
draft proposal of xcat-inventory+ git integration

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-inventory#90]
target:
1. encapsulate git operations in xcat-inventory interface 
2. shield off the complexity of git usage for xcat-inventory user
3. use git as a backend of xcat-inventory to manage revisions and tags of inventory data

configuration file:
1. inventory configuration file: `/etc/xcat/inventory.cfg` , which specifies:
* the upstream git repo url: `<url-upstream-repo>`
* git credential(user/passwd or token): `<credential>`
* the path of local repo: `<local-repo-path>`
* the default workspace(branch) of local repo to operate on: `<branch>`

each user has its own inventory config file under `/home/<user>/.xcat/inventory.cfg`. if the config file does not exist, will use the default config file `/etc/xcat/inventory.cfg`

CLI:

Phase 1: 
###########################################
* `xcat-inventory init` : 
   - initialize the backend git configuration with the inventory configuration file
   - clone the upstream repo if not cloned before
   - sync the upstream repo with local repo
   - checkout to default workspace
* `xcat-inventory workspace new/delete/list/select`
    - relevant with git branch operations
* `xcat-inventory list-rev <rev>`:
   - list all the tags in the current branch
   - `git show <rev>` if `<rev>` specified
* `xcat-inventory checkout <rev>`:
   - `git checkout <rev>`
   - `xcat-inventory import`
* `xcat-inventory commit -m <message> [revision]`:
   - export current inventory data from xCAT DB to git backend
   - `git add` to stage all the exported inventory data
   - create a commit/tag in backend git repo

* `xcat-inventory push`:
   - commit the current inventory data in backend git repo, push to the upstream repo
   - sync the remote branch with backend local repo
* `xcat-inventory sync`:
   - sync the current branch of local repo with remote repo with upstream repo
   - `git pull upstream <branch> --tags`

* `xcat-inventory envlist`:
   - show all the environment variables xcat-inventory exposes
 
###########################################

Phase 2: 
###########################################
* `xcat-inventory validate`:
   - validate the current inventory data in backend git repo
* `xcat-inventory diff`:
   - show the difference between the current inventory data in backend git repo and the inventory data in xCAT DB
###########################################

Phase 3: 
###########################################
*  `xcat-inventory graph`:
   - shows the graph of object relationships like definition dependency, connection topology which can be obtained from the current xCAT inventory data in backend git repo
   - show the graph based on the inventory data in current xCAT DB
   - show the action plan 
* `xcat-inventory apply`:
   - import current version of inventory data in local git repo to xCAT DB
   - perform relevant underlie actions in the cluster

###########################################

**Comment by immarvin** [comment]
updates on discussion(2018/08/23):
1. the cluster infrastructure inventory and osimages should be managed in 2 separate backend git repos. 
2. the interface of osimage management should be considered

**Comment by immarvin** [comment]
the xcat-image CLI draft design:
1. configuration file /etc/xcat/inventory.cfg:
 * xcat osimage upstream repo url
 * xcat osimage local repo path
 * xcat osimage default osimage workspace(branch)
 * the remote path of 3rd party software shared dir 
 * the local mount point of the  3rd party software shared dir

2. CLI:
`xcat-image  init` :
* clone the upstream repo to local repo path if not cloned before
* sync the local repo with upstream repo
* checkout the default workspace
* mount the 3rd party software shared dir if not

`xcat-image list`
* list all the osimages in the workspace

`xcat-image `

**Comment by zet809** [comment]
Let's close this task, @immarvin is working the prototype based on the discussion above.

**Comment by daniceexi** [comment]
I'd like to know whether we have made basic agreement against the design before making prototype?

**Comment by immarvin** [comment]
hi @daniceexi , based on the discussion, we do not see opposite comments on the items in "phase 1" and "phase 2". Most of the arguments are on "phase 3" items.  

So I'd like to start the prototype on basic git integration work in "phase 1", xuwei will start the work on `xcat-inventory diff` on "phase 2".  The discussion on "phase 3" items will go on in the following discussions.

During the following development work, there might be updates on the design. minor modifications  will be discussed on daily interlock or scrum meeting, major modifications will call for a discussion meeting

**Comment by daniceexi** [comment]
@immarvin Good, thanks for the information.

**Comment by whowutwut** [comment]
I still do not clearly see the use case for running `xcat-inventory diff` and I need to be convinced that this is needed.   I think this requirement still assumes that we are testing changes by making drect changes to xCAT, and then testing it... then we want to see what really changed so we can merge it back into source control.   This will equate potential user error in the merge. 

I am still in the mindset and have been practicing making changes directly to source control... create a pull request in the branch.... switch branches to test the changes and test by importing the changes to xCAT, rather than making changes via xCAT CLI.  

Because once it's tested, the changes are Ready to be directly deployed into PRODUCTION.... having a method to detect changes, then export, and commit back to source control results in UNTESTED change and always comes with a slight risk that we deploy something that was not 100% tested, human error comes into the picture.

**Comment by robin2008** [comment]
Per my understanding,  the spirit of GitOps is to using Git/PR as the base of Infrastructure as code.
But as we know, in version control, the resource, policy, codes, configurations are only declarative.  It still needs the action you apply it onto the infrastructure to take effective.

- For declarative, the target is for sharing. And if you want to share with more organizations for different environment,  you need variables. Ansible, Puppet, Terraform,  they all supports variables, it is the key to abstract the common business logic and make it customizable.

- For apply/diff,  the target is to take action and make the result as your expected. It is a key in GitOps,  maybe your policy does not require to do something,  this is only means the action is `none`

We can understand  your use case in HPC-devops. You try to make Gitops without customization and  no extra actions, that's great.  This is one user scenario to leverage `xcat-invetory` to do the GitOps, and I think currently the tool can support it, and we will continue to fill the gap for the case.   

In another way,  we still want make `xcat-inventory` be more general in Infrastructure as Code,  so we can use it outside of IBM.  For example,  we can publish our `osimage` inventory for ICP,  PowerAI, GPFS in xcat.org,  we can also publish cluster inventory for different topology, and customer just pull them and apply onto their immutable infrastructure with minor customization. 

Currently, Infrastructure management mostly are automation, there are not many hard technical thing. Then the public sharing is becoming the key factor. Ansible/puppet/terraform can do such things well, that's a key reason why they are so popular.

**Comment by robin2008** [comment]
@whowutwut @immarvin 
I think we still need more discussion on the case and design.

**Comment by immarvin** [comment]
Besides the big picture @robin2008 mentioned above,  I would like to give several use cases of  `xcat-inventory diff` (take the feature in PR https://github.com/xcat2/xcat-inventory/pull/107 as an example)

1. `xcat-inventory diff --files <file A> <file B>` provides an object based diff for inventory files, compared with line based `diff`:

(1)  prepare the inventory data
```
 # xcat-inventory export -t node -o mid05tor12cn13,mid05tor12cn15 -f /tmp/nodes
 # xcat-inventory export -t node -o mid05tor12cn12,mid05tor12cn14,mid05tor12cn13 -f /tmp/nodes2
```

(2)  the line based inventory diff

```
# diff /tmp/nodes /tmp/nodes2
1a2,17
>   mid05tor12cn12:
>     device_info:
>       arch: ppc64le
>     device_type: server
>     engines:
>       console_engine:
>         engine_info:
>           consoleenabled: '1'
>       netboot_engine:
>         engine_info:
>           osimage: rhels7.4-snap2-ppc64le-install-compute
>           postscripts: fake
>     obj_info:
>       groups: group1,all,compute,cn_regex
>     obj_type: node
>     role: compute
12c28,30
<   mid05tor12cn15:
---
>   mid05tor12cn14:
>     device_info:
>       arch: ppc64le
17a36,39
>       netboot_engine:
>         engine_info:
>           osimage: rhels7.4-snap2-ppc64le-install-compute
>           postscripts: fake
19c41
<       groups: all,compute,cn_regex,witherspoon,dd21
---
>       groups: group1,all,compute,cn_regex
```

confusing, is it?

(3) Now the object based diff, 

```
# xcat-inventory diff --files /tmp/nodes /tmp/nodes2

====================BEGIN=====================


--- /tmp/nodes
+++ /tmp/nodes2
node:
+  mid05tor12cn12:
+    device_info:
+      arch: ppc64le
+    device_type: server
+    engines:
+      console_engine:
+        engine_info:
+          consoleenabled: '1'
+      netboot_engine:
+        engine_info:
+          osimage: rhels7.4-snap2-ppc64le-install-compute
+          postscripts: fake
+    obj_info:
+      groups: group1,all,compute,cn_regex
+    obj_type: node
+    role: compute
+  mid05tor12cn14:
+    device_info:
+      arch: ppc64le
+    device_type: server
+    engines:
+      console_engine:
+        engine_info:
+          consoleenabled: '1'
+      netboot_engine:
+        engine_info:
+          osimage: rhels7.4-snap2-ppc64le-install-compute
+          postscripts: fake
+    obj_info:
+      groups: group1,all,compute,cn_regex
+    obj_type: node
+    role: compute
-  mid05tor12cn15:
-    device_type: server
-    engines:
-      console_engine:
-        engine_info:
-          consoleenabled: '1'
-    obj_info:
-      groups: all,compute,cn_regex,witherspoon,dd21
-    obj_type: node
-    role: compute


====================END=====================
```

2. Before admin apply the inventory data just pulled down from git, it is important for admin to understand what changes will be imposed on the cluster from the diff output. This diff result result is also the key information to trigger the underline xCAT actions to deploy the cluster according to applied the inventory data.

3. There is scenario to push the inventory data from xCAT DB to the upstream git repo. Consider the discovery case,  initially, we just have some predefined inventory data, then we run discovery and get the full inventory data, we need to push the full inventory data up to git repo, since we do not need to rediscover all objects from scratch each time.

**Comment by immarvin** [comment]
close this task

**Comment by immarvin** [comment]
close this task
